import os
import sys
import glob
import subprocess
import argparse
import re
from PIL import Image

def get_habit_and_level(filename):
    """Parse 'habit-lvX.ext' or similar to get the habit name and level."""
    base = os.path.basename(filename)
    name, ext = os.path.splitext(base)
    # Check if the format is '[habit]-lv[level]'
    match = re.match(r'^([a-zA-Z0-9_-]+)-lv(\d+)$', name, re.IGNORECASE)
    if match:
        return match.group(1).lower(), int(match.group(2))
    # Fallback to plain name (e.g., just 'meditation')
    return name.lower(), 1

def run_rembg(input_path, output_path):
    print(f"Removing background for {os.path.basename(input_path)}...")
    try:
        # Using absolute path since it was installed in roaming AppData and isn't on PATH
        rembg_exe = r"C:\Users\erenk\AppData\Roaming\Python\Python314\Scripts\rembg.exe"
        if not os.path.exists(rembg_exe):
             rembg_exe = "rembg" # fallback
        subprocess.run([rembg_exe, "i", input_path, output_path], check=True)
        return True
    except subprocess.CalledProcessError:
        print(f"Error: Failed to process {input_path} with rembg.")
        return False
    except FileNotFoundError:
        print("Error: `rembg` CLI not found. Please install via: pip install rembg --break-system-packages")
        sys.exit(1)

def process_image(img_path, target_size, margin=16):
    print(f"Cropping and resizing {os.path.basename(img_path)}...")
    try:
        with Image.open(img_path) as img:
            img = img.convert("RGBA")
            
            # Find bounding box of non-transparent areas
            bbox = img.getbbox()
            if not bbox:
                print(f"Warning: {img_path} is completely transparent.")
                return img
                
            left, upper, right, lower = bbox
            img_cropped = img.crop((left, upper, right, lower))
            
            # Calculate target dimensions for the cropped part
            # We want the final image to be exactly `target_size x target_size`.
            # We need to fit the crop into `(target_size - 2*margin)`.
            max_inner_size = target_size - 2 * margin
            ow, oh = img_cropped.size
            scale = min(max_inner_size / ow, max_inner_size / oh)
            
            new_w = int(ow * scale)
            new_h = int(oh * scale)
            
            # Use nearest neighbor to preserve straight/pixelated lines
            img_resized = img_cropped.resize((new_w, new_h), Image.NEAREST)
            
            # Create a new transparent image of `target_size x target_size`
            final_img = Image.new("RGBA", (target_size, target_size), (0, 0, 0, 0))
            
            # Center the resized image within the final square
            offset_x = (target_size - new_w) // 2
            offset_y = target_size - new_h - margin  # Bottom align is usually better for isometric buildings
            
            final_img.paste(img_resized, (offset_x, offset_y), img_resized)
            return final_img
            
    except Exception as e:
        print(f"Error processing {img_path}: {e}")
        return None

def update_manifest(registry, manifest_path):
    print(f"Generating sprite manifest at {manifest_path}...")
    
    os.makedirs(os.path.dirname(manifest_path), exist_ok=True)
    
    lines = [
        "// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.",
        "// Generated by asset-pipeline skill (process-assets.py)",
        "",
        "export const BUILDING_SPRITES: Record<string, Record<number, string>> = {"
    ]
    
    for habit in sorted(registry.keys()):
        lines.append(f"  {habit}: {{")
        for level in sorted(registry[habit].keys()):
            asset_path = registry[habit][level]
            lines.append(f"    {level}: '{asset_path}',")
        lines.append("  },")
        
    lines.append("};")
    lines.append("")
    
    with open(manifest_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))

def main():
    parser = argparse.ArgumentParser(description="Process building assets: remove background, crop, resize.")
    parser.add_argument("--input", default="assets/raw", help="Path to raw images folder")
    parser.add_argument("--output", default="public/assets/town/buildings", help="Path to output processed images")
    parser.add_argument("--temp", default="assets/processed", help="Path to intermediate (rembg output) folder")
    parser.add_argument("--size", type=int, default=512, help="Target uniform bounding box size (e.g. 512 for 512x512)")
    parser.add_argument("--manifest", default="src/modules/town/data/building-sprites.ts", help="Path to write TS manifest")
    args = parser.parse_args()

    os.makedirs(args.input, exist_ok=True)
    os.makedirs(args.output, exist_ok=True)
    os.makedirs(args.temp, exist_ok=True)

    input_files = []
    for ext in ("*.png", "*.jpg", "*.jpeg", "*.webp"):
        input_files.extend(glob.glob(os.path.join(args.input, ext)))

    if not input_files:
        print(f"No image files found in {args.input}/")
        print("Please place files named like 'meditation-lv1.png' there first.")
        sys.exit(0)

    print(f"Found {len(input_files)} image(s) to process.")
    
    registry = {}

    for file_path in input_files:
        habit, level = get_habit_and_level(file_path)
        base = os.path.basename(file_path)
        name, _ = os.path.splitext(base)
        
        # 1. Background removal
        rembg_output = os.path.join(args.temp, f"{name}.png")
        if not os.path.exists(rembg_output): # skip if already processed
            success = run_rembg(file_path, rembg_output)
            if not success:
                continue
        else:
            print(f"Using cached rembg output for {name}")
            
        # 2 + 3. Crop and resize
        final_filename = f"{habit}-lv{level}.png"
        final_output_path = os.path.join(args.output, final_filename)
        
        final_img = process_image(rembg_output, args.size, margin=16)
        if final_img:
            final_img.save(final_output_path, "PNG")
            print(f"Saved processed output to {final_output_path}")
            
            # Register for manifest
            if habit not in registry:
                registry[habit] = {}
            # Public assets are referenced starting from /assets/...
            asset_ref = f"/assets/buildings/{final_filename}"
            registry[habit][level] = asset_ref

    # 5. Generate Manifest
    if registry:
        update_manifest(registry, args.manifest)
        print("Asset pipeline complete!")
    else:
        print("No assets processed successfully.")

if __name__ == "__main__":
    main()
